### ISSUE TITLE
powsimR installation error

### ISSUE THREAD

**Issue by xiuweiz** [bvieth/powsimR#28]
Dear Beate,

I followed this page to install powsimR: https://github.com/bvieth/powsimR/blob/master/vignettes/powsimR.Rmd

and got the following output with error `Error : object ‘fitDE’ is not exported by 'namespace:DECENT'
ERROR: lazy loading failed for package ‘powsimR’`. I tried re-installing DECENT but that didn't help.

The output looks like this:
```
> devtools::install_github('bvieth/powsimR', 
+                          build_vignettes = TRUE, 
+                          dependencies=FALSE)
Downloading GitHub repo bvieth/powsimR@master
from URL https://api.github.com/repos/bvieth/powsimR/zipball/master
Installing powsimR
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD build '/tmp/Rtmp7stA6V/devtools34d029f5bcda/bvieth-powsimR-f3e43ef'  \
  --no-resave-data --no-manual 

* checking for file ‘/tmp/Rtmp7stA6V/devtools34d029f5bcda/bvieth-powsimR-f3e43ef/DESCRIPTION’ ... OK
* preparing ‘powsimR’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘powsimR’ ...
** R
** data
*** moving datasets to lazyload DB
No protocol specified
Warning in rgl.init(initValue, onlyNULL) :
  RGL: unable to open X11 display
Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE
** inst
** byte-compile and prepare package for lazy loading
Error : object ‘fitDE’ is not exported by 'namespace:DECENT'
ERROR: lazy loading failed for package ‘powsimR’
* removing ‘/tmp/RtmpYxTxl2/Rinst484acdd3492/powsimR’
      -----------------------------------
ERROR: package installation failed
Installation failed: Command failed (1)
```

Many thanks,
Xiuwei

**Comment by bvieth** [comment]
Dear Xiuwei,

thank you for pointing that out. Since I did not update my dependencies recently, I missed the changes in DECENT that resulted in this installation error. I have updated powsimR accordingly and the new version 1.1.3 should work now.

Kind regards
Beate

**Comment by xiuweiz** [comment]
Thank you very much Beate!
Indeed, I can install and load powsimR now. Although I still get some warnings, I hope it doesn't affect running the simulation.
```
** testing if installed package can be loaded
Warning: replacing previous import ‘DECENT::lrTest’ by ‘MAST::lrTest’ when loading ‘powsimR’
Warning in rgl.init(initValue, onlyNULL) :
  RGL: unable to open X11 display
Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE
Warning: replacing previous import ‘parallel::makeCluster’ by ‘snow::makeCluster’ when loading ‘powsimR’
Warning: replacing previous import ‘parallel::stopCluster’ by ‘snow::stopCluster’ when loading ‘powsimR’
Warning: replacing previous import ‘penalized::predict’ by ‘stats::predict’ when loading ‘powsimR’
Warning: replacing previous import ‘zinbwave::glmWeightedF’ by ‘zingeR::glmWeightedF’ when loading ‘powsimR’
* DONE (powsimR)
```

**Comment by bvieth** [comment]
Dear Xiuwei,

that looks good. Indeed there are some warnings because certain functions share the same name across implemented packages. But this should not be a problem. 
I will close the issue for now. Feel free to reopen / start a new thread if you need any further assistance.

Kind regards
Beate
